### ISSUE TITLE
Error getting google images

### ISSUE THREAD

**Issue by quintendewilde** [CumminUp07/imengine#1]
I get following error when trying to get the google images. 

```
python get_google_images.py
Traceback (most recent call last):
  File "get_google_images.py", line 77, in <module>
    search_images(base, terms, 1000)
  File "get_google_images.py", line 71, in search_images
    all_links = get_links(base[y]+'+'+terms[x], num_images)
  File "get_google_images.py", line 28, in get_links
    json_string = urllib2.urlopen(request).read()
  File "/home/quinten/anaconda2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/quinten/anaconda2/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/quinten/anaconda2/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/quinten/anaconda2/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/home/quinten/anaconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/quinten/anaconda2/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

```

**Comment by Aeryes** [comment]
Is this still an open issue?

**Comment by ghost** [comment]
Yes this issue is still there
